In [2]:
import csv
import pandas as pd
import pymongo
from pymongo import MongoClient

In [3]:
#Connect to MongoDB database
client = MongoClient("mongodb://%s:%s@127.0.0.1" % ("dap", "dap")) #Secured connection
# client = MongoClient("localhost",27017)
# client = MongoClient("mongodb://localhost:27017/")

db = client['dap']
collection = db['total_housing_data']

In [4]:
df = pd.read_csv(r"..\reqd_datasets\total-housing-units-by-town-2019.csv")
print(df.head(10))

      Town       FIPS       Year Occupancy Status Measure Type  \
0  Andover  901301080  2006-2010            Total       Number
1  Andover  901301080  2006-2010            Total       Number
2  Andover  901301080  2006-2010           Vacant       Number
3  Andover  901301080  2006-2010           Vacant       Number
4  Andover  901301080  2006-2010           Vacant      Percent
5  Andover  901301080  2006-2010           Vacant      Percent
6  Andover  901301080  2006-2010         Occupied       Number
7  Andover  901301080  2006-2010         Occupied       Number
8  Andover  901301080  2006-2010         Occupied      Percent
9  Andover  901301080  2006-2010         Occupied      Percent

           Variable    Value
0     Housing Units  1286.00
1  Margins of Error    77.00
2     Housing Units    10.00
3  Margins of Error    15.00
4     Housing Units     0.78
5  Margins of Error     1.17
6     Housing Units  1276.00
7  Margins of Error    76.00
8     Housing Units    99.22
9  Margins of Error     8.38

In [5]:
#reading CSV file "total-housing-units-by-town-2019.csv" from folder "reqd_datasets"
with open(r"..\reqd_datasets\total-housing-units-by-town-2019.csv") as csvfile:
    csvdata = csv.DictReader(csvfile)
    for row_data in csvdata:
        collection.insert_one(row_data)

In [6]:
# data retrieval from a MongoDB database named "db" in a collection named "total_housing_data"
retrieved_data = db.total_housing_data
retrieved_data = pd.DataFrame(list(retrieved_data.find()))

In [7]:
# Displaying the count of null values in dataset for every column
retrieved_data.isnull().sum()

_id                 0
Town                0
FIPS                0
Year                0
Occupancy Status    0
Measure Type        0
Variable            0
Value               0
dtype: int64

In [8]:
retrieved_data

,_id,Town,FIPS,Year,Occupancy Status,Measure Type,Variable,Value
0,6a24647f541378fac5cd6c40,Andover,0901301080,2006-2010,Total,Number,Housing Units,1286
1,6a24647f541378fac5cd6c41,Andover,0901301080,2006-2010,Total,Number,Margins of Error,77
2,6a24647f541378fac5cd6c42,Andover,0901301080,2006-2010,Vacant,Number,Housing Units,10
3,6a24647f541378fac5cd6c43,Andover,0901301080,2006-2010,Vacant,Number,Margins of Error,15
4,6a24647f541378fac5cd6c44,Andover,0901301080,2006-2010,Vacant,Percent,Housing Units,0.78
...,...,...,...,...,...,...,...,...
33995,6a296a95de9a3110fe5b3713,Woodstock,0901588190,2015-2019,Vacant,Percent,Margins of Error,4.92
33996,6a296a95de9a3110fe5b3714,Woodstock,0901588190,2015-2019,Occupied,Number,Housing Units,3249
33997,6a296a95de9a3110fe5b3715,Woodstock,0901588190,2015-2019,Occupied,Number,Margins of Error,200
33998,6a296a95de9a3110fe5b3716,Woodstock,0901588190,2015-2019,Occupied,Percent,Housing Units,88.36
33999,6a296a95de9a3110fe5b3717,Woodstock,0901588190,2015-2019,Occupied,Percent,Margins of Error,7.62

In [9]:
# Dropping the unnecessary columns
retrieved_data = retrieved_data.drop(['_id'],axis=1)
retrieved_data

,Town,FIPS,Year,Occupancy Status,Measure Type,Variable,Value
0,Andover,0901301080,2006-2010,Total,Number,Housing Units,1286
1,Andover,0901301080,2006-2010,Total,Number,Margins of Error,77
2,Andover,0901301080,2006-2010,Vacant,Number,Housing Units,10
3,Andover,0901301080,2006-2010,Vacant,Number,Margins of Error,15
4,Andover,0901301080,2006-2010,Vacant,Percent,Housing Units,0.78
...,...,...,...,...,...,...,...
33995,Woodstock,0901588190,2015-2019,Vacant,Percent,Margins of Error,4.92
33996,Woodstock,0901588190,2015-2019,Occupied,Number,Housing Units,3249
33997,Woodstock,0901588190,2015-2019,Occupied,Number,Margins of Error,200
33998,Woodstock,0901588190,2015-2019,Occupied,Percent,Housing Units,88.36
33999,Woodstock,0901588190,2015-2019,Occupied,Percent,Margins of Error,7.62

In [10]:
# Identify duplicate rows
print("Duplicate rows: ",retrieved_data.duplicated().sum())
print("Shape of the data: ",retrieved_data.shape)

Duplicate rows:  17000
Shape of the data:  (34000, 7)

In [11]:
from sqlalchemy import create_engine
import psycopg2

engine = create_engine('postgresql+psycopg2://dap:dap@127.0.0.1:5432/postgres')
postgreSQLConnection    = engine.connect()
postgreSQLTable         = "total_housing_units_data"

try:
    retrieved_data.to_sql(postgreSQLTable, postgreSQLConnection, if_exists='replace');
except ValueError as vx:
    print(vx)
except Exception as ex: 
    print(ex)
else:
    print("PostgreSQL Table %s has been created successfully."%postgreSQLTable);
finally:
    postgreSQLConnection.close();

PostgreSQL Table total_housing_units_data has been created successfully.