In [1]:
from sqlalchemy import create_engine
import psycopg2
import pandas as pd

# Creating an engine instance
alchemyEngine = create_engine('postgresql+psycopg2://dap:dap@127.0.0.1:5432/postgres')

# Connecting to PostgreSQL server
dbConnection = alchemyEngine.connect()

# Reading data from PostgreSQL database table and load into a DataFrame instance
real_estate_data = pd.read_sql("select * from \"real_estate_dataset\"", dbConnection);
affordable_housing_data = pd.read_sql("select * from \"affordable_housing_data\"", dbConnection);
total_housing_units_data = pd.read_sql("select * from \"total_housing_units_data\"", dbConnection);

pd.set_option('display.expand_frame_repr', False);

# Close the database connection
dbConnection.close();

In [2]:
# Dropping the index columns
real_estate_data = real_estate_data.drop(['index'],axis=1)
affordable_housing_data = affordable_housing_data.drop(['index'],axis=1)
total_housing_units_data = total_housing_units_data.drop(['index'],axis=1)

In [3]:
# Merging the datasets one by one
merge_real_estate_affordable_data = real_estate_data.merge(affordable_housing_data, how="inner", on = ['Year', 'Town']);
# merge_real_estate_affordable_data

In [4]:
# Showing dataset columns and datatypes
merge_real_estate_affordable_data.dtypes

Year                                    object
Town                                    object
Assessed Value                         float64
Sale Amount                            float64
Property Type                           object
Residential Type                        object
Sales Ratio                            float64
Town Code                               object
Census Units                            object
Government Assisted                     object
Tenant Rental Assistance                object
 Single Family CHFA/ USDA Mortgages     object
Deed Restricted Units                   object
Total Assisted Units                    object
Percent Affordable                      object
dtype: object

In [5]:
# Showing dataset columns and datatypes
total_housing_units_data.dtypes

Town                           object
Year Range                     object
Housing Units: Total          float64
Margins of Error: Total       float64
Housing Units: Vacant         float64
Margins of Error: Vacant      float64
Housing Units: Occupied       float64
Margins of Error: Occupied    float64
dtype: object

In [6]:
 merged_real_estate_affordable_data = merge_real_estate_affordable_data

In [7]:
import pandas as pd

# Convert Year columns to datetime format
merged_real_estate_affordable_data['Year'] = pd.to_datetime(merged_real_estate_affordable_data['Year'], format='%Y').dt.year
# merged_real_estate_affordable_data
len(merged_real_estate_affordable_data.loc[merged_real_estate_affordable_data['Year'] >= 2015])

3208

In [8]:
# Split Year range column into two separate columns
total_housing_units_data[['Start year', 'End year']] = total_housing_units_data['Year Range'].str.split('-', expand=True)

# Convert Start year and End year columns to datetime format
total_housing_units_data['Start year'] = pd.to_datetime(total_housing_units_data['Start year'], format='%Y').dt.year
total_housing_units_data['End year'] = pd.to_datetime(total_housing_units_data['End year'], format='%Y').dt.year

# total_housing_units_data

In [9]:
len(total_housing_units_data.loc[total_housing_units_data['Start year'] >= 2015])

170

In [10]:
total_housing_units_data.dtypes

Town                           object
Year Range                     object
Housing Units: Total          float64
Margins of Error: Total       float64
Housing Units: Vacant         float64
Margins of Error: Vacant      float64
Housing Units: Occupied       float64
Margins of Error: Occupied    float64
Start year                      int64
End year                        int64
dtype: object

In [11]:
# Merge with condition
merged_df = pd.merge(merged_real_estate_affordable_data, total_housing_units_data, how="inner", on='Town')
merged_df = merged_df[(merged_df['Year'] >= merged_df['Start year']) & (merged_df['Year'] <= merged_df['End year'])]
merged_df

       Year       Town  Assessed Value  Sale Amount  Property Type Residential Type  Sales Ratio Town Code Census Units Government Assisted  ... Percent Affordable Year Range Housing Units: Total Margins of Error: Total Housing Units: Vacant Margins of Error: Vacant  Housing Units: Occupied  Margins of Error: Occupied  Start year  End year
1      2011    Andover       1106800.0   1412000.00  Single Family    Single Family     0.783853         1         1317                  24  ...               3.42  2007-2011               1233.0                    87.0                  30.0                     37.0                   1203.0                        92.0        2007      2011
2      2011    Andover       1106800.0   1412000.00  Single Family    Single Family     0.783853         1         1317                  24  ...               3.42  2008-2012               1153.0                    82.0                  18.0                     29.0                   1135.0                        83.0        2008      2012
3      2011    Andover       1106800.0   1412000.00  Single Family    Single Family     0.783853         1         1317                  24  ...               3.42  2009-2013               1144.0                    79.0                  40.0                     43.0                   1104.0                        78.0        2009      2013
4      2011    Andover       1106800.0   1412000.00  Single Family    Single Family     0.783853         1         1317                  24  ...               3.42  2010-2014               1195.0                    78.0                  50.0                     52.0                   1145.0                        78.0        2010      2014
5      2011    Andover       1106800.0   1412000.00  Single Family    Single Family     0.783853         1         1317                  24  ...               3.42  2011-2015               1234.0                    92.0                  76.0                     60.0                   1158.0                        84.0        2011      2015
...     ...        ...             ...          ...            ...              ...          ...       ...          ...                 ...  ...                ...        ...                  ...                     ...                   ...                      ...                      ...                         ...         ...       ...
48999  2018  Woodstock       1253800.0   2106415.17          Condo            Condo     0.595229       169         3582                  24  ...               1.59  2015-2019               3677.0                   222.0                 428.0                    179.0                   3249.0                       200.0        2015      2019
49008  2018  Woodstock      22945570.0  37464565.00  Single Family    Single Family     0.612461       169         3582                  24  ...               1.59  2014-2018               3510.0                   240.0                 467.0                    194.0                   3043.0                       224.0        2014      2018
49009  2018  Woodstock      22945570.0  37464565.00  Single Family    Single Family     0.612461       169         3582                  24  ...               1.59  2015-2019               3677.0                   222.0                 428.0                    179.0                   3249.0                       200.0        2015      2019
49019  2019  Woodstock        907000.0   1444500.00          Condo            Condo     0.627899       169         3582                  24  ...               1.59  2015-2019               3677.0                   222.0                 428.0                    179.0                   3249.0                       200.0        2015      2019
49029  2019  Woodstock      26601600.0  44341364.00  Single Family    Single Family     0.599927       169         3582                  24  ...               1.59  2015-2019               3677.0                   222.0                 428.0                    179.0                   3249.0                       200.0        2015      2019

[15214 rows x 24 columns]

In [12]:
# Reset the index of the grouped dataframe and add a serial number as a new index
merged_df = merged_df.reset_index().reset_index(drop=True)

In [13]:
merged_df = merged_df.drop(['index', 'Year Range', 'Town Code', 'Census Units', 'Start year', 'End year'],axis=1)

In [14]:
print("Duplicate rows: ",merged_df.duplicated().sum())

Duplicate rows:  0

In [15]:
merged_df.columns

Index(['Year', 'Town', 'Assessed Value', 'Sale Amount', 'Property Type',
       'Residential Type', 'Sales Ratio', 'Government Assisted',
       'Tenant Rental Assistance', ' Single Family CHFA/ USDA Mortgages',
       'Deed Restricted Units', 'Total Assisted Units', 'Percent Affordable',
       'Housing Units: Total', 'Margins of Error: Total',
       'Housing Units: Vacant', 'Margins of Error: Vacant',
       'Housing Units: Occupied', 'Margins of Error: Occupied'],
      dtype='object')

In [20]:
# cols_to_match = ['Serial Number', 'Town', 'Year', 'Address', 'Sale Amount']
cols_to_match = ['Town', 'Year', 'Sale Amount']
new_merged_df = merged_df.groupby(cols_to_match).agg({'Year':'first','Town':'first','Assessed Value': 'first', 'Sale Amount': 'first', 
                                                  'Sales Ratio': 'first', 'Property Type': 'first','Residential Type': 'first', 
                                                  'Government Assisted': 'first','Tenant Rental Assistance': 'first',
                                                  ' Single Family CHFA/ USDA Mortgages': 'first', 'Deed Restricted Units': 'first',
                                                  'Total Assisted Units': 'first', 'Percent Affordable': 'first',
                                                  'Housing Units: Total': 'mean', 'Margins of Error: Total': 'mean',
                                                  'Housing Units: Vacant': 'mean', 'Margins of Error: Vacant': 'mean', 
                                                  'Housing Units: Occupied': 'mean','Margins of Error: Occupied': 'mean'})
new_merged_df

                            Year       Town  Assessed Value  Sale Amount  Sales Ratio  Property Type Residential Type Government Assisted Tenant Rental Assistance  Single Family CHFA/ USDA Mortgages Deed Restricted Units Total Assisted Units Percent Affordable  Housing Units: Total  Margins of Error: Total  Housing Units: Vacant  Margins of Error: Vacant  Housing Units: Occupied  Margins of Error: Occupied
Town      Year Sale Amount
Andover   2011 1412000.00   2011    Andover       1106800.0   1412000.00     0.783853  Single Family    Single Family                  24                        1                                  20                     0                   45               3.42           1191.800000                83.600000              42.800000                 44.200000              1149.000000                        83.0
          2012 125000.00    2012    Andover        132800.0    125000.00     1.062400     Two Family       Two Family                  24                        1                                  22                     0                   47               3.57           1201.000000                83.600000              53.600000                 49.600000              1147.400000                        79.6
               7136924.00   2012    Andover       5412060.0   7136924.00     0.758318  Single Family    Single Family                  24                        1                                  22                     0                   47               3.57           1201.000000                83.600000              53.600000                 49.600000              1147.400000                        79.6
          2013 825000.00    2013    Andover        386820.0    825000.00     0.468873     Two Family       Two Family                  24                        1                                  29                     0                   54                4.1           1237.600000                84.800000              73.800000                 56.800000              1163.800000                        80.6
               5921285.00   2013    Andover       4461700.0   5921285.00     0.753502  Single Family    Single Family                  24                        1                                  29                     0                   54                4.1           1237.600000                84.800000              73.800000                 56.800000              1163.800000                        80.6
...                          ...        ...             ...          ...          ...            ...              ...                 ...                      ...                                 ...                   ...                  ...                ...                   ...                      ...                    ...                       ...                      ...                         ...
Woodstock 2017 41962232.00  2017  Woodstock      27345090.0  41962232.00     0.651660  Single Family    Single Family                  24                        0                                  48                     0                   72               2.01           3566.666667               240.666667             442.333333                183.333333              3124.333333                       219.0
          2018 2106415.17   2018  Woodstock       1253800.0   2106415.17     0.595229          Condo            Condo                  24                        0                                  33                     0                   57               1.59           3593.500000               231.000000             447.500000                186.500000              3146.000000                       212.0
               37464565.00  2018  Woodstock      22945570.0  37464565.00     0.612461  Single Family    Single Family                  24                        0                                  33                     0                   57               1.59           3593.500000               231.000000             447.500000                186.500000              3146.000000                       212.0
          2019 1444500.00   2019  Woodstock        907000.0   1444500.00     0.627899          Condo            Condo                  24                        0                                  33                     0                   57               1.59           3677.000000               222.000000             428.000000                179.000000              3249.000000                       200.0
               44341364.00  2019  Woodstock      26601600.0  44341364.00     0.599927  Single Family    Single Family                  24                        0                                  33                     0                   57               1.59           3677.000000               222.000000             428.000000                179.000000              3249.000000                       200.0

[3966 rows x 19 columns]

In [21]:
merged_df = new_merged_df.reset_index(drop=True)
merged_df

      Year       Town  Assessed Value  Sale Amount  Sales Ratio  Property Type Residential Type Government Assisted Tenant Rental Assistance  Single Family CHFA/ USDA Mortgages Deed Restricted Units Total Assisted Units Percent Affordable  Housing Units: Total  Margins of Error: Total  Housing Units: Vacant  Margins of Error: Vacant  Housing Units: Occupied  Margins of Error: Occupied
0     2011    Andover       1106800.0   1412000.00     0.783853  Single Family    Single Family                  24                        1                                  20                     0                   45               3.42           1191.800000                83.600000              42.800000                 44.200000              1149.000000                        83.0
1     2012    Andover        132800.0    125000.00     1.062400     Two Family       Two Family                  24                        1                                  22                     0                   47               3.57           1201.000000                83.600000              53.600000                 49.600000              1147.400000                        79.6
2     2012    Andover       5412060.0   7136924.00     0.758318  Single Family    Single Family                  24                        1                                  22                     0                   47               3.57           1201.000000                83.600000              53.600000                 49.600000              1147.400000                        79.6
3     2013    Andover        386820.0    825000.00     0.468873     Two Family       Two Family                  24                        1                                  29                     0                   54                4.1           1237.600000                84.800000              73.800000                 56.800000              1163.800000                        80.6
4     2013    Andover       4461700.0   5921285.00     0.753502  Single Family    Single Family                  24                        1                                  29                     0                   54                4.1           1237.600000                84.800000              73.800000                 56.800000              1163.800000                        80.6
...    ...        ...             ...          ...          ...            ...              ...                 ...                      ...                                 ...                   ...                  ...                ...                   ...                      ...                    ...                       ...                      ...                         ...
3961  2017  Woodstock      27345090.0  41962232.00     0.651660  Single Family    Single Family                  24                        0                                  48                     0                   72               2.01           3566.666667               240.666667             442.333333                183.333333              3124.333333                       219.0
3962  2018  Woodstock       1253800.0   2106415.17     0.595229          Condo            Condo                  24                        0                                  33                     0                   57               1.59           3593.500000               231.000000             447.500000                186.500000              3146.000000                       212.0
3963  2018  Woodstock      22945570.0  37464565.00     0.612461  Single Family    Single Family                  24                        0                                  33                     0                   57               1.59           3593.500000               231.000000             447.500000                186.500000              3146.000000                       212.0
3964  2019  Woodstock        907000.0   1444500.00     0.627899          Condo            Condo                  24                        0                                  33                     0                   57               1.59           3677.000000               222.000000             428.000000                179.000000              3249.000000                       200.0
3965  2019  Woodstock      26601600.0  44341364.00     0.599927  Single Family    Single Family                  24                        0                                  33                     0                   57               1.59           3677.000000               222.000000             428.000000                179.000000              3249.000000                       200.0

[3966 rows x 19 columns]

In [22]:
# Creating Engine Instances and establishing the connection and pushing dataframe to the database

engine = create_engine('postgresql+psycopg2://dap:dap@127.0.0.1:5432/postgres')
postgreSQLConnection    = engine.connect()
postgreSQLTable = "merged_data_table"

try:
    merged_df.to_sql(postgreSQLTable, postgreSQLConnection, if_exists='replace');
except ValueError as vx:
    print(vx)
except Exception as ex: 
    print(ex)
else:
    print("PostgreSQL Table %s has been created successfully."%postgreSQLTable);
finally:
    postgreSQLConnection.close();

PostgreSQL Table merged_data_table has been created successfully.